# Generated by Django 4.1.3 on 2022-12-02 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='price_per_item',
        ),
    ]
