# Generated by Django 4.1.3 on 2022-12-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_price_order_price_per_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price_per_item',
            new_name='price',
        ),
    ]
